name: frontend ci

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build:
    name: build and push to docker
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "22"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: frontend

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build
        run: npm run build
        working-directory: frontend

      - name: Set up QEMU
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:frontend"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:v${{ github.run_number }}
